### ISSUE TITLE
Rune.jar hasn't been updated since 2021/11/06

### ISSUE THREAD

**Issue by dginovker** [RSCPlus/WinRune#8]
https://github.com/RSCPlus/WinRune/commit/ab7e6c8f4bfff8ffedccffbc64eb10764f567dd0

The OpenRSC launcher grabs the .jar from the master branch in this repo, so people playing via OpenRSC have been missing all the changes (& bugfixes) since

**Comment by lmsv-mx123** [comment]
Closing since all set by now
